cqRobot:
  port: 6700

user:
  groupID: 730074397
  jspath: C:/repeater/js
  logpath: C:/repeater/log
  privateKey: praiseBang
  javapath: C:/repeater/java
  classpath: C:/repeater/class
  dbpath: C:/repeater/db