spring:
  mvc:
    view:
      prefix: "classpath:/templates/"
      suffix: ".html"
  profiles:
    include: user
  servlet:
    multipart:
      max-file-size: 5KB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  tomcat:
    uri-encoding: UTF-8
  port: 80